eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9091
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: firstModule
          uri: http://localhost:9090/
          predicates:
            - Path= /associates/**


